
package com.xjwfk.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.xjwfk.domain.Customer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.xjwfk.com/")
@XmlSeeAlso({
   
})
public interface CustomerService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomersToDecidedzone", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.AssignCustomersToDecidedzone")
    @ResponseWrapper(localName = "assignCustomersToDecidedzoneResponse", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.AssignCustomersToDecidedzoneResponse")
    public void assignCustomersToDecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @return
     *     returns java.util.List<com.xjwfk.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNotAssociate", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindNotAssociate")
    @ResponseWrapper(localName = "findNotAssociateResponse", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindNotAssociateResponse")
    public List<Customer> findNotAssociate();

    /**
     * 
     * @return
     *     returns java.util.List<com.xjwfk.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.xjwfk.service.Customer>
     */
    @WebMethod(operationName = "findBy_decidedzone_id")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBy_decidedzone_id", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindByDecidedzoneId")
    @ResponseWrapper(localName = "findBy_decidedzone_idResponse", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindByDecidedzoneIdResponse")
    public List<Customer> findByDecidedzoneId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.xjwfk.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findIsAssociate", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindIsAssociate")
    @ResponseWrapper(localName = "findIsAssociateResponse", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindIsAssociateResponse")
    public List<Customer> findIsAssociate();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedIdzoneByAddr", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindDecidedIdzoneByAddr")
    @ResponseWrapper(localName = "findDecidedIdzoneByAddrResponse", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindDecidedIdzoneByAddrResponse")
    public String findDecidedIdzoneByAddr(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.xjwfk.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.xjwfk.com/", className = "com.xjwfk.service.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
